# Generated by Django 6.0 on 2026-02-02 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adventurer',
            name='invested_class',
            field=models.TextField(blank=True, default='[]', verbose_name='Classes investidas'),
        ),
        migrations.AlterField(
            model_name='adventurer',
            name='tshirt_size',
            field=models.CharField(choices=[('02', '02'), ('04', '04'), ('06', '06'), ('08', '08'), ('10', '10'), ('12', '12'), ('PP', 'PP'), ('P', 'P'), ('M', 'M'), ('G', 'G'), ('GG', 'GG')], max_length=4, verbose_name='Tamanho da camiseta'),
        ),
    ]
