# Generated by Django 6.0 on 2026-02-02 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_adventurer_invested_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='bronquite',
            field=models.BooleanField(default=False, verbose_name='Bronquite'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='catapora',
            field=models.BooleanField(default=False, verbose_name='Catapora'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='caxumba',
            field=models.BooleanField(default=False, verbose_name='Caxumba'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='colera',
            field=models.BooleanField(default=False, verbose_name='Cólera'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='coqueluche',
            field=models.BooleanField(default=False, verbose_name='Coqueluche'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='dengue',
            field=models.BooleanField(default=False, verbose_name='Dengue'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='difteria',
            field=models.BooleanField(default=False, verbose_name='Difteria'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='febre_amarela',
            field=models.BooleanField(default=False, verbose_name='Febre Amarela'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='h1n1',
            field=models.BooleanField(default=False, verbose_name='H1N1'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='hepatite',
            field=models.BooleanField(default=False, verbose_name='Hepatite'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='malaria',
            field=models.BooleanField(default=False, verbose_name='Malária'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='meningite',
            field=models.BooleanField(default=False, verbose_name='Meningite'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='pneumonia',
            field=models.BooleanField(default=False, verbose_name='Pneumonia'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='rinite',
            field=models.BooleanField(default=False, verbose_name='Rinite'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='rubelola',
            field=models.BooleanField(default=False, verbose_name='Rubéola'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='sarampo',
            field=models.BooleanField(default=False, verbose_name='Sarampo'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='tetano',
            field=models.BooleanField(default=False, verbose_name='Tétano'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='variola',
            field=models.BooleanField(default=False, verbose_name='Varíola'),
        ),
    ]
