# Generated by Django 6.0 on 2026-02-02 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_medicalrecord_bronquite_medicalrecord_catapora_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsible',
            name='address_number',
            field=models.CharField(blank=True, max_length=10, verbose_name='Número'),
        ),
    ]
